WVD Scenario content
Azure/WellArchitected-Assessment pull request #372
Opened 2021-08-02 06:51 UTC by heoelri

Summary of changes proposed in this pull request:

Follow-up PR for https://github.com/Azure/WellArchitected-Assessment/pull/201 and https://github.com/Azure/WellArchitected-Assessment/pull/371 - @JamJarchitect 

> IMPORTANT: Make sure you are familiar with the [Contributing](/Contributing.md) guidance. Particularly, **don't edit \*.md files directly - make your changes in the source \*.json files**.

2021-08-05 09:42 UTC, JamJarchitect commented on data/scenariolens-wvd.data.json
> +        "title": "Design your storage to reside as close as possible to your session hosts",
It's a good point, I have since amended this to read clearer

2021-08-05 09:47 UTC, JamJarchitect commented on data/scenariolens-wvd.data.json
> +        "context": "All files inside the VHD would be scanned on demand",
Another good point. Future tense inevitable term 👍

2021-08-05 09:51 UTC, JamJarchitect commented on data/scenariolens-wvd.data.json
> +      "title": "The hybrid identity solution in this instance would be Azure AD Connect",
So Azure AD Join is currently in preview. When working with CAF I always stick by the rule of "If it's not GA, it's not going into considerations/recommendations." Are we doing the same with our assessments @sebader & @heoelri ?

Also working on the wording just now

2021-08-05 10:18 UTC, heoelri commented on data/scenariolens-wvd.data.json
> +      "title": "The hybrid identity solution in this instance would be Azure AD Connect",
Not sure if we've ever agreed on clear guidelines here. What we've done is that we do not recommend preview / non-GA features and services, but we sometimes call them out and mention them with a clear note that they're in preview.

2021-08-05 11:17 UTC, heoelri commented
Btw. @JamJarchitect is WVD still the correct name or is it now Azure Virtual Desktop?

2021-08-06 06:28 UTC, heoelri commented
Sorry @JamJarchitect i was a bit too quick with merging PR #377 into this branch. You've to modify the json files only. I've incorporated your changes here, now.

2021-08-06 06:33 UTC, heoelri commented
@sitarant anything to add from your side?

2021-08-20 12:43 UTC, msimecek requested changes

2021-08-20 12:43 UTC, msimecek commented on data/categories.json
> +    "title": "AVD",
I would prefer this to be expanded - "Azure Virtual Desktop" - like for example "Azure Kubertnetes Service (AKS)".

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +      "scenario/AVD"
Unlike in the category name, here for brevity I would leave it as "avd" - it's an internal reference anyway.

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "[Storage sizing for Azure Files and Azure NetApp Files](https://docs.microsoft.com/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#performance-requirements
```suggestion
        "context": "[Storage sizing for Azure Files and Azure NetApp Files](https://docs.microsoft.com/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#performance-requirements) needs to align with IOPS requirements.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "Active Directory Domain Services line of site",
```suggestion
        "title": "Active Directory Domain Services line of sight",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +      "scenario/AVD"
```suggestion
      "scenario/avd"
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "(Storage) Storage requirements should be optimized for performance in the Azure Virtual Desktop service",
```suggestion
        "title": "Storage requirements should be optimized for performance in the Azure Virtual Desktop service",
```

I think these are unnecessary.

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "(Storage) Size of the volumes should reflect the performance needed",
```suggestion
        "title": "Size of the storage volumes should reflect the performance needed",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "(Storage - Azure Files) SKU of the Azure Files Storage Account",
```suggestion
        "title": "SKU of the Azure Files Storage Account",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "FSLogix Cloud Cache is used for best practice failover and quick recovery scenarios",
```suggestion
        "context": "FSLogix Cloud Cache is used for best practice failover and quick recovery scenarios.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Azure Files ([Azure AD Domain Services](https://docs.microsoft.com/azure/virtual-desktop/create-profile-container-adds) or [Active Directory Domain Services](https://docs.microsof
```suggestion
        "context": "Azure Files ([Azure AD Domain Services](https://docs.microsoft.com/azure/virtual-desktop/create-profile-container-adds) or [Active Directory Domain Services](https://docs.microsoft.com/azure/virtual-desktop/create-file-share), [Azure NetApp Files](https://docs.microsoft.com/azure/virtual-desktop/create-fslogix-profile-container), [VM-based file share](https://docs.microsoft.com/azure/virtual-desktop/create-host-pools-user-profile)).",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Light users - Standard File Shares, Medium users - Standard/Premium File Shares, Heavy users - Premium File Shares, Power users - Premium File Shares",
```suggestion
        "context": "Light users - Standard File Shares, Medium users - Standard/Premium File Shares, Heavy users - Premium File Shares, Power users - Premium File Shares.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "It is just as vital to implement a backup solution next to your disaster recovery solution. [Azure NetApps Files supports scheduled snapshots](https://docs.microsoft.com/azure/azu
```suggestion
        "context": "It is just as vital to implement a backup solution next to your disaster recovery solution. [Azure NetApps Files supports scheduled snapshots](https://docs.microsoft.com/azure/azure-netapp-files/azure-netapp-files-manage-snapshots) and Azure Backup should be considered for [File Shares](https://docs.microsoft.com/azure/backup/azure-file-share-backup-overview).",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "This increases performance and latency for a better end user experience",
This increases latency for better user experience? :D

```suggestion
        "context": "This increases performance and improves latency for a better end user experience.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "All files inside the VHD would be scanned on demand",
```suggestion
        "context": "All files inside the VHD would be scanned on demand.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Ensure that your network architecture has enough internal IP addresses to support the number of AVD Session Hosts in your environment",
```suggestion
        "context": "Ensure that your network architecture has enough internal IP addresses to support the number of AVD Session Hosts in your environment.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "Set up [Azure AD Connect](https://docs.microsoft.com/azure/active-directory/hybrid/whatis-azure-ad-connect).",
```suggestion
        "title": "Set up [Azure AD Connect](https://docs.microsoft.com/azure/active-directory/hybrid/whatis-azure-ad-connect)",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "AVD Users must be sourced from the same Active Directory Domain Service (ADDS) that is synchronising to Azure AD. AVD does not support B2B or Microsoft Accounts.",
"B2B" or "B2C"? I'm not sure here...

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Synchronize all identities to a single Azure AD using Azure AD Connect",
```suggestion
        "context": "Synchronize all identities to a single Azure AD using Azure AD Connect.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "During the session host building phase/automation the account used to work on those hosts cannot have multi-factor authentication",
```suggestion
        "context": "During the session host building phase/automation the account used to work on those hosts cannot have multi-factor authentication.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Segregate the AVD Session Host Virtual Machines (VMs) into Active Directory Organizational Units (OUs) for each host pool to manage policies and orphaned objects",
```suggestion
        "context": "Segregate the AVD Session Host Virtual Machines (VMs) into Active Directory Organizational Units (OUs) for each host pool to manage policies and orphaned objects.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Create policies for AVD. For example, multi-factor authentication can be enforced on conditions such as risky sign-ins increasing an organizations security posture",
```suggestion
        "context": "Create policies for AVD. For example, multi-factor authentication can be enforced on conditions such as risky sign-ins increasing an organizations security posture.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "Azure Monitor allows for a central location around log and monitoring data in Azure",
```suggestion
        "context": "Azure Monitor provides a central location for log and monitoring data in Azure.",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "It is recommended to enable [performance counters for AVD](https://docs.microsoft.com/azure/virtual-desktop/azure-monitor#set-up-performance-counters)",
```suggestion
        "context": "It is recommended to enable [performance counters for AVD](https://docs.microsoft.com/azure/virtual-desktop/azure-monitor#set-up-performance-counters).",
```

2021-08-20 12:43 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "context": "AVD [EnableBackupScript](https://github.com/Azure/RDS-Templates/tree/master/EnableBackupScript) can be used to back up AVD Session Hosts",
```suggestion
        "context": "AVD [EnableBackupScript](https://github.com/Azure/RDS-Templates/tree/master/EnableBackupScript) can be used to back up AVD Session Hosts.",
```

2021-09-01 07:53 UTC, msimecek commented on data/categories.json
> +    "title": "AVD",
Done.

2021-09-01 10:49 UTC, msimecek commented on data/scenariolens-avd.data.json
> +        "title": "AVD Users must be sourced from the same Active Directory Domain Service (ADDS) that is synchronising to Azure AD. AVD does not support B2B or Microsoft Accounts.",
No response, so I'll leave it as it is.

2021-09-01 10:50 UTC, msimecek approved these changes

2021-09-01 11:49 UTC, sitarant commented
> @sitarant anything to add from your side?

No, all good from my site, thanks

2021-09-01 12:58 UTC, sebader commented on data/categories.json
> +    "title": "Azure Virtual Desktop (AVD)",
why do we need the abbreviation in the category in the first place? we dont have it on any other categories?

2021-09-01 12:59 UTC, msimecek commented on data/categories.json
> +    "title": "Azure Virtual Desktop (AVD)",
Because it's used extensively in text, so I figured it would help to have it explained in the header.

2021-09-01 13:01 UTC, msimecek commented on data/categories.json
> +    "title": "Azure Virtual Desktop (AVD)",
AKS has it too.

2021-09-01 13:05 UTC, sebader commented on data/categories.json
> +    "title": "Azure Virtual Desktop (AVD)",
ok fine then

2021-09-01 13:05 UTC, sebader approved these changes

2021-09-01 14:26 UTC, merged